// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz7Km3rG4FLpr1NVvwrdirfL3V4GDHh6w',
    appId: '1:458625647709:web:3cd8fc1356e4d9a3d079b4',
    messagingSenderId: '458625647709',
    projectId: 'mat-app-bc99c',
    authDomain: 'mat-app-bc99c.firebaseapp.com',
    storageBucket: 'mat-app-bc99c.firebasestorage.app',
    measurementId: 'G-FRHXC2Y38Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhPpkCTvhEYqqsd2UEd5hSijEK1TiWQHs',
    appId: '1:458625647709:android:fb3658283ccf3f01d079b4',
    messagingSenderId: '458625647709',
    projectId: 'mat-app-bc99c',
    storageBucket: 'mat-app-bc99c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxG_Rs26lMZmNMZ6fmXqyuReniFuAX9Ig',
    appId: '1:458625647709:ios:462e02ff76141d66d079b4',
    messagingSenderId: '458625647709',
    projectId: 'mat-app-bc99c',
    storageBucket: 'mat-app-bc99c.firebasestorage.app',
    iosBundleId: 'com.example.matApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxG_Rs26lMZmNMZ6fmXqyuReniFuAX9Ig',
    appId: '1:458625647709:ios:462e02ff76141d66d079b4',
    messagingSenderId: '458625647709',
    projectId: 'mat-app-bc99c',
    storageBucket: 'mat-app-bc99c.firebasestorage.app',
    iosBundleId: 'com.example.matApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz7Km3rG4FLpr1NVvwrdirfL3V4GDHh6w',
    appId: '1:458625647709:web:05b80c201e885ca3d079b4',
    messagingSenderId: '458625647709',
    projectId: 'mat-app-bc99c',
    authDomain: 'mat-app-bc99c.firebaseapp.com',
    storageBucket: 'mat-app-bc99c.firebasestorage.app',
    measurementId: 'G-8BT9VQMNNK',
  );

}